#!/bin/bash

if [ ! -d "/home/jovyan/work" ]; then
    mkdir -p /home/jovyan/work
fi

if [ ! -f "/home/jovyan/work/.seeded" ]; then
    cp /var/dist/content/* /home/jovyan/work/
    touch /home/jovyan/work/.seeded
fi

fix-permissions $HOME


if [ -f "/var/startup/start_jh_extras" ]; then
    sudo /var/startup/start_jh_extras
fi


# Service file: /lib/systemd/system/postgresql.service
sudo service postgresql restart

# Service file available at: /lib/systemd/system/mongod.service
#sudo /var/startup/start_mongo
sudo mongod --fork --logpath /dev/stdout --dbpath ${MONGO_DB_PATH}


# Test dir
#if [ -d "$DIR" ]; then
#fi

# Test file
#if [ -f "$FILE" ]; then
#fi

exec "$@" 
