ARG BASE_IMAGE=python:3.8 
# Uses debian buster
FROM ${BASE_IMAGE}

ARG PROCESSOR_FAMILY=x86_64
ENV PROCESSOR_FAMILY=${PROCESSOR_FAMILY}

# Create a base Python environment on which to build other images
