name: buildx-vce-tm351-monolith
# Via: https://www.padok.fr/en/blog/multi-architectures-docker-iot
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Push to dockerhub'

jobs:
  buildx_vce_tm351_monolith:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Build the images, without pushing
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ouvocl/vce-tm351-monolith:${GITHUB_SHA::7} \
            ./tm351-monolith
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Reusing the cache, push the images
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ouvocl/vce-tm351-monolith:${GITHUB_SHA::7} \
            ./tm351-monolith \
            --push
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ouvocl/vce-tm351-monolith:latest \
            ./tm351-monolith \
            --push
 
  
