name: buildx-vce-pandas
# Via: https://www.padok.fr/en/blog/multi-architectures-docker-iot
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Push to dockerhub'

jobs:
  buildx_vce_pandas:
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Build the images, without pushing
      - name: Run Buildx linux/amd64
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ouvocl/vce-pandas:${GITHUB_SHA::7} \
            --build-arg BASE_IMAGE=ouvocl/vce-notebook \
            ./pandas-notebook
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Reusing the cache, push the images
      - name: Push linux/amd64
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ouvocl/vce-pandas:${GITHUB_SHA::7} \
            --build-arg BASE_IMAGE=ouvocl/vce-notebook \
            ./pandas-notebook \
            --push
          docker buildx build \
            --platform linux/amd64 \
            -t ouvocl/vce-pandas:latest \
            --build-arg BASE_IMAGE=ouvocl/vce-notebook \
            ./pandas-notebook \
            --push
          docker rmi -f ouvocl/vce-pandas:${GITHUB_SHA::7}
          docker rmi -f ouvocl/vce-pandas:latest
      - name: Build and push linux/arm64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ouvocl/vce-pandas:${GITHUB_SHA::7} \
            --build-arg BASE_IMAGE=ouvocl/vce-notebook \
            ./pandas-notebook \
            --push
          docker buildx build \
            --platform linux/arm64 \
            -t ouvocl/vce-pandas:latest \
            ./pandas-notebook \
            --push
          docker rmi -f ouvocl/vce-pandas:${GITHUB_SHA::7}
          docker rmi -f ouvocl/vce-pandas:latest
      - name: Build and push linux/arm7
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -t ouvocl/vce-pandas:${GITHUB_SHA::7} \
             -f ./pandas-notebook/Dockerfile.arm32 \
             --build-arg BASE_IMAGE=ouvocl/vce-notebook \
            ./pandas-notebook \
            --push
          docker buildx build \
            --platform linux/arm/v7 \
            -t ouvocl/vce-pandas:latest \
            -f ./pandas-notebook/Dockerfile.arm32 \
            --build-arg BASE_IMAGE=ouvocl/vce-notebook \
            ./pandas-notebook \
            --push

